// REGISTRATION
export const REGISTER_BY_EMAIL = "REGISTER_BY_EMAIL";

// LOGIN
export const GET_VK_LOCATION = "GET_VK_LOCATION";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER";
export const LOGIN_BY_EMAIL = "LOGIN_BY_EMAIL";
export const RESET_USER = "RESET_USER";
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT";
export const LOGOUT = "LOGOUT";
